backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "sectors" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Sectors" # Used in the UI, ie.: "New Post"
    folder: "site/data/sectors" # The path to the folder where the documents are stored
    extension: "yml"
    slug: "{{id}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Id", name: "id", widget: "string" }
      - { label: "Priority", name: "priority", widget: "number" }
      - { label: "Image", name: "img", widget: "image", required: true }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "services" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Services" # Used in the UI, ie.: "New Post"
    folder: "site/data/services" # The path to the folder where the documents are stored
    extension: "yml"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Id", name: "id", widget: "string" }
      - { label: "Priority", name: "priority", widget: "number" }
      - { label: "Image", name: "img", widget: "image", required: true }
      - { label: "Description", name: "description", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Image, name: image, widget: image }
          - {
              label: "About Us",
              name: about,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - {
              label: "Expertise",
              name: "expertise",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - {
              label: "Recruitment",
              name: recruitment,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Logo, name: logo, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/sectors/_index.md"
        label: "Sectors Page"
        name: "sectors"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: text, widget: string }
          - { label: Image, name: image, widget: image }
          - label: sectors
            name: sectors
            widget: list
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Text, name: text, widget: text }
              - { label: Image1, name: img1, widget: image }
              - { label: Image2, name: img2, widget: image }
      - file: "site/content/services/_index.md"
        label: "Services Page"
        name: "services"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: text, widget: string }
          - { label: Image, name: image, widget: image }
          - label: services
            name: services
            widget: list
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Text, name: text, widget: text }
              - { label: Image1, name: img1, widget: image }
              - { label: Image2, name: img2, widget: image }
